title: Pedro Maglione
logo: https://github.com/pmaglione/pmaglione.github.io/blob/master/logo.png
description: Pedro Maglione Page.
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
